# Generated by Django 6.0.4 on 2026-05-09 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_organization_owner_alter_membership_role"),
        ("purchases", "0002_templatepurchase_organization"),
        ("templates_catalog", "0002_templatepackage_license_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("preparing", "Preparing"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("github_repo_url", models.URLField(blank=True, max_length=512)),
                (
                    "zip_file",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_projects/zips/"
                    ),
                ),
                ("deployment_url", models.URLField(blank=True, max_length=512)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_projects",
                        to="organizations.organization",
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_project",
                        to="purchases.templatepurchase",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_projects",
                        to="templates_catalog.saastemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Project",
                "verbose_name_plural": "Generated Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex code or CSS color name",
                        max_length=20,
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        help_text="Target payment provider (e.g., Stripe, Paystack)",
                        max_length=50,
                    ),
                ),
                ("cms_enabled", models.BooleanField(default=True)),
                (
                    "deployment_target",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Vercel, Railway, Heroku",
                        max_length=100,
                    ),
                ),
                ("extra_config", models.JSONField(blank=True, default=dict)),
                (
                    "generated_project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="generator.generatedproject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
