# Generated by Django 6.0.4 on 2026-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepackage',
            name='license_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('commercial', 'Commercial'), ('agency', 'Agency')], default='personal', max_length=20),
        ),
    ]
