# Generated by Django 6.0.4 on 2026-05-04 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('templates_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('project_url', models.URLField(blank=True, help_text="The live URL of the client's project")),
                ('repository_url', models.URLField(blank=True, help_text="The repository URL for the client's project")),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_projects', to='purchases.templatepurchase')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_projects', to='templates_catalog.saastemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeploymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building'), ('deployed', 'Deployed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('delivery_link', models.URLField(blank=True, help_text='Link to the codebase (ZIP, GitHub repo, etc.)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_requests', to='deployments.clientproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
