# Generated by Django 6.0.4 on 2026-05-08 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customizationrequest",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customization_requests",
                to="organizations.organization",
            ),
        ),
    ]
