# Generated by Django 6.0.4 on 2026-05-09 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_organization_owner_alter_membership_role"),
        ("purchases", "0002_templatepurchase_organization"),
        ("templates_catalog", "0002_templatepackage_license_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("license_key", models.CharField(max_length=255, unique=True)),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("commercial", "Commercial"),
                            ("agency", "Agency"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                ("allowed_end_products", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_licenses",
                        to="organizations.organization",
                    ),
                ),
                (
                    "purchase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license",
                        to="purchases.templatepurchase",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="templates_catalog.saastemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template License",
                "verbose_name_plural": "Template Licenses",
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=50)),
                ("release_date", models.DateField()),
                ("changelog", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_latest", models.BooleanField(default=False)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates_catalog.saastemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Version",
                "verbose_name_plural": "Template Versions",
                "ordering": ["-release_date", "-created_at"],
                "unique_together": {("template", "version")},
            },
        ),
    ]
