# Generated by Django 6.0.4 on 2026-05-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managedfile",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("template_screenshot", "Template Screenshot"),
                    ("client_brand_asset", "Client Brand Asset"),
                    ("delivery_zip", "Delivery Zip"),
                    ("invoice", "Invoice"),
                    ("document", "Document"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
